# Generated by Django 5.2.8 on 2025-12-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_slug',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery')], default='cash_on_delivery', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProductMetaInformation',
        ),
    ]
