# Generated by Django 5.2.8 on 2026-01-02 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variation_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variation_name', models.CharField(help_text="e.g., '0.5 KG', '1 KG', 'Large', 'Family Pack'", max_length=100)),
                ('variation_price', models.IntegerField(help_text='Price for this variation')),
                ('variation_demo_price', models.IntegerField(blank=True, help_text='Original price (for discount display)', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Available stock for this variation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product')),
            ],
            options={
                'ordering': ['variation_price'],
                'unique_together': {('product', 'variation_name')},
            },
        ),
    ]
