# Generated by Django 5.2.8 on 2026-01-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_product_is_available_product_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_measuring',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('ML', 'Milliliter'), ('L', 'Liter'), ('PIECE', 'Piece'), ('In', 'Inches'), ('NONE', 'None')], default='NONE', max_length=100),
        ),
    ]
