# Generated by Django 5.2.8 on 2026-01-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_uuid_remove_order_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='stock_quantity',
        ),
    ]
